# -*- coding: utf-8 -*-
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAddgroup():
    def setup_method(self, method):
        self.wd = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.wd.quit()

    def logout(self):
        # logout
        self.wd.find_element(By.LINK_TEXT, "Logout").click()

    def createGroup(self, group_name, group_header, group_footer):
        # create group
        self.wd.find_element(By.LINK_TEXT, "groups").click()
        self.wd.find_element(By.NAME, "new").click()
        self.wd.find_element(By.NAME, "group_name").click()
        self.wd.find_element(By.NAME, "group_name").send_keys(group_name)
        self.wd.find_element(By.NAME, "group_header").send_keys(group_header)
        self.wd.find_element(By.NAME, "group_footer").send_keys(group_footer)
        self.wd.find_element(By.NAME, "submit").click()

    def login(self, username, password):
        # login
        self.wd.set_window_size(1489, 873)
        self.wd.find_element(By.NAME, "user").send_keys(username)
        self.wd.find_element(By.NAME, "pass").send_keys(password)
        self.wd.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()

    def openHomePage(self):
        # open hone page
        self.wd.get("http://127.0.0.1/addressbook/index.php")

    # run test
    def test_addgroup(self):
        self.openHomePage()
        self.login("admin", "secret")
        self.createGroup("auto_test", "new auto_test", "new auto_test")
        self.logout()

    def test_empty_addgroup(self):
        self.openHomePage()
        self.login("admin", "secret")
        self.createGroup("", "", "")
        self.logout()