# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAuthorizationandcreategroup():
    def setup_method(self, method):
        self.wd = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.wd.quit()

    def test_authorizationandcreategroup(self):
        self.wd.get("http://127.0.0.1/addressbook/index.php")
        self.wd.set_window_size(550, 692)
        self.wd.find_element(By.NAME, "user").send_keys("admin")
        self.wd.find_element(By.ID, "LoginForm").click()
        self.wd.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
        self.wd.find_element(By.LINK_TEXT, "groups").click()
        self.wd.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
        self.wd.find_element(By.NAME, "group_name").click()
        self.wd.find_element(By.NAME, "group_name").send_keys("test_group")
        self.wd.find_element(By.NAME, "group_header").send_keys("header group")
        self.wd.find_element(By.NAME, "group_footer").send_keys("footer group")
        self.wd.find_element(By.NAME, "submit").click()
